### ISSUE TITLE
Item Types Node

### ISSUE THREAD

**Issue by edashbolt** [edashbolt/generative-components#3]
Create a node to read / write data to items

**Comment by CJAndrew84** [comment]
Ed, Thanks for sharing this. 

Loading the project into Visual Studios 2019, i have got the following error for Item Types - 
![image](https://user-images.githubusercontent.com/50639116/104165839-d32b8300-53f1-11eb-852a-2f7cbf59c087.png)

Line 107. 'Feature.Element()' is a method, which is not valid in the given context.

When i try and use the Item Types Write Node function, assuming all the input are correct i get  -
![image](https://user-images.githubusercontent.com/50639116/104166056-171e8800-53f2-11eb-931b-7815a8b38d88.png)

Any Chance you know the fix. I'm too new at C# and GC to know, yet

**Comment by edashbolt** [comment]
Hi Andrew,
It looks like you are running this in OpenRoads, can I ask which version of ORD you are using? I have only tested this in OpenBuildings Update 6; I imagine this is likely a version incompatibility issue, since there have been some changes made to GC in the more recent updates

**Comment by CJAndrew84** [comment]
Hi Ed
Using ORD 2020 r3 10.09
Thought changes like that might be the issue

**Comment by edashbolt** [comment]
Not sure which build that would be in terms of GC, but I just spoke with Alifur from Bentley and he confirmed that he had a similar issue with my source code on the latest build due to changes in the GC library. You could try the following and see if this works:

```
// At line 107 in the "ItemTypes class, change the following method:
long eleID = feat.Element.ID;

//to instead be the following:
long eleID = feat.ComElement().ID;
```

BTW I will get around to upgrading my source code to be compliant with the latest GC libraries soon, the only reason I haven't done it yet is that I have a project requirement to use this specific version of OpenBuildings and I didn't want to have multiple versions installed in parallel!

**Comment by CJAndrew84** [comment]
I'll swap that out this morning. Thanks Ed.
It may be useful to keep both. Never now when you need the old and new versions.

**Comment by CJAndrew84** [comment]
Ed,
Amended that bit of the code, and that cleared the error in VS.
I also removed the [] from string[] for PropertyName and PropertyValue and got the following exception raised when dubugging
![image](https://user-images.githubusercontent.com/50639116/104568488-1121e480-5648-11eb-84e5-dca48557e71e.png)
Added the [] back in and the same error is raised

**Comment by CJAndrew84** [comment]
Fixed it!

At line107 it is long eleID = feat.ComElement().ID

![image](https://user-images.githubusercontent.com/50639116/104585451-eb9ed600-565b-11eb-9bb9-b3ee81515a95.png)

**Comment by edashbolt** [comment]
Right sorry about that, my mistake! I was just copying and pasting what someone else had written and didn't look through it properly... Yes we want to obtain the Feature "feat" element ID, so that we can then get this element as a DGNPlatformNET.Elements.Element type, so you nailed it! Good work 👍

**Comment by edashbolt** [comment]
> Ed,
> Amended that bit of the code, and that cleared the error in VS.
> I also removed the [] from string[] for PropertyName and PropertyValue and got the following exception raised when dubugging
> ![image](https://user-images.githubusercontent.com/50639116/104568488-1121e480-5648-11eb-84e5-dca48557e71e.png)
> Added the [] back in and the same error is raised

You can remove the [] if you like (this will make it a single string object instead of a string array), however you will also need to remove the for loop since this would still be iterating over that parameter (which is a single string) hence the error you received. The reason I have this as an array is so that you can update multiple item type properties, like this:
![ItemTypes](https://user-images.githubusercontent.com/37052856/104656790-fe74e180-5713-11eb-9314-f7d6e3a5b23b.PNG)

This gives us more flexibility down the road when we have this requirement. You can still specify your inputs as a single string within an array like so: {'Property1'} if you only want to update a single item type property. Hope that makes sense!

**Comment by edashbolt** [comment]
Item type node completed with updated logic for ease of use

**Comment by CJAndrew84** [comment]
Hi Ed,
I'm using the new version, and coming up against an issue with Item Types, not persisting after export to a separate DGN file.
Are you seeing this problem also?
